### ISSUE TITLE
Campo de RIF

### ISSUE THREAD

**Issue by ozzybracho** [Vauxoo/odoo-venezuela#20]
Hola. He estado probando Odoo 7 con los paquetes de addons de odoo-venezuela y estoy teniendo un problema. Cuando voy a añadir una compañía, me sale el mensaje "El RIF debe ser único o estar vacío para poder procesarlo y guardarlo". Eso a pesar de que coloco el número de RIF en los campos "ID de impuesto" y "Registro de compañía".

**Comment by nhomar** [comment]
el rif debe estar en la forma:

VEJXXXXXXS

Nota el VE al principio.
