### ISSUE TITLE
ovl - Error de instalación

### ISSUE THREAD

**Issue by ozzybracho** [Vauxoo/odoo-venezuela#37]
Al momento de instalar el módulo ovl surge un error, y realizando la instalación individual el error parece ligado al módulo fiscal_requirements:

Se adjunta el log

[Odoo Error.txt](https://github.com/Vauxoo/odoo-venezuela/files/150118/Odoo.Error.txt)

**Comment by nhomar** [comment]
Versión?

El error te dice que tienes la precisión de Account en 4 en el core y cuando instalas explota.

Esto está probado solo para la 7.0 para la8.0 no ha sido completamente revisada, y no está en planes hacerlo en un futuro cercano.

¿Que versión estás instalando?

**Comment by ozzybracho** [comment]
Versión 8.0

La precisión no la tengo establecida porque lo estoy haciendo sin instalar el módulo contable primero, dejando que el script lo hiciera. Debo instalar primero el contable, establecer la precisión a 2 para que funcione?

**Comment by nhomar** [comment]
Esa verificación no estaba en la 7.0 pruebalo y nos cuentas, si se soluciona fino, sino posiblemente evita hacer set del rounding de cualquier cosa aquí en la localización.... es decir edita los archivos xml que lo estén haciendo....

Si lo resuelves un PR is welcome.

**Comment by ozzybracho** [comment]
Ya hice las pruebas respectivas.
El problema se origina porque la configuración de la moneda VEF viene por defecto con precisión 4. El único modo de cambiarla si no se ha instalado el módulo de contabilidad, es en editar la empresa y en la pestaña donde se selecciona la moneda, elegir VEF y luego hacer click en la flecha que tiene a un lado. Esto nos lleva a la ventana de configuración de monedas, donde se puede establecer la precisión y los decimales. 
Una vez cambiado esto, el ovl funciona bien e instala todos los módulos necesarios. En todo caso, en alguna modificación a futuro, el script no se si está en la capacidad de ajustar este campo de la moneda antes de iniciar la instalación.

**Comment by rzavarce** [comment]
Muy buenos días, antes que nada permítanme felicitarlos por su iniciativa en el desarrollo de software libre, soy también un entusiasta y estoy en prueba de Odoo en su versión 8.0. 

Mi pregunta se centra en como realizar la instalación de la localización, he descargado los archivos pero conozco muy poco sobre Odoo. Que debo hacer, que me recomiendan para iniciarme en este gran sistema ERP

**Comment by reliakk** [comment]
Saludos,

Estoy tratando de instalar el modulo de ovl en la version 9 de odoo, pero me da varios bugs,

El mas comun es:

Error details:
View inheritance may not use attribute 'string' as a selector

Buscando por foros, me dicen que el modulo que intento instalar es para version 8, en otros que haga esto:

·································································································

Same error with xpath

xpath expr="//group[@string='Params']" position="after"

The solution is:

xpath expr="//group" position="after"

or

xpath expr="/FULL_XML_TREE/group" position="after"

··························································

De antemano muchas gracias, si me puede dar alguna ayuda o info al respecto.

**Comment by hbto** [comment]
buenas tardes @reliakk 

La localización aún no está migrada a versión 9.0

Estás a completa disposición de ti, poder realizar
PR, para hacer los fixes correspondientes y hacer que la 
localización funcione en odoo9.0, con lo cual apreciaremos
grandemente tu aporte.

Si no tienes el tiempo y dispones de financiamiento
te invitamos a que colabores financiando la migración
de la misma a versión 9.0, con lo cual te ofrecemos
nuestros productos y servicios para que puedas lograr
tu cometido.

Saludos

**Comment by hbto** [comment]
> Ya hice las pruebas respectivas.
> El problema se origina porque la configuración de la moneda VEF viene por defecto con precisión 4. El único modo de cambiarla si no se ha instalado el módulo de contabilidad, es en editar la empresa y en la pestaña donde se selecciona la moneda, elegir VEF y luego hacer click en la flecha que tiene a un lado. Esto nos lleva a la ventana de configuración de monedas, donde se puede establecer la precisión y los decimales. 
> Una vez cambiado esto, el ovl funciona bien e instala todos los módulos necesarios. En todo caso, en alguna modificación a futuro, el script no se si está en la capacidad de ajustar este campo de la moneda antes de iniciar la instalación.

Dado que este problema se considera resuelto, entonces procedo a cerrar este issue
